<?php
declare(strict_types=1);

use Hyva\Theme\ViewModel\HyvaCsp;
?>
<script>
    window.addEventListener('checkout:init:main', event => {
        hyvaCheckout.evaluation.registerValidator('validateInpostLocker', async (element, component) => {
            return new Promise((resolve, reject) => {
                let currentLocker = component.get('locker');
                if (null !== currentLocker) {
                    resolve(true);
                } else {
                    reject(false);
                }
            });
        });
    });
</script>
<?php
/** @var HyvaCsp $hyvaCsp */
$hyvaCsp->registerInlineScript();
?>
