<button id="inpost-select-picker" type="button" class="action update btn btn-secondary">
    <?= /* @noEscape */ __('Select pickup point') ?>
</button>
<div id="inpost-locker-logo-wrapper"></div>
<div id="inpost_locker-selected" style="display:none">
    <div>
        <strong><?= /* @noEscape */ __('Selected locker:') ?></strong>
        <span id="inpost_locker-code"></span>
    </div>
    <div id="inpost_locker-address"></div>
</div>
<div id="inpost-modal-wrapper">
    <div class="inpost-modal-content">
        <a href="#" class="inpost-modal-close" id="inpost-modal-close"></a>
        <div id="inpost-map-container"></div>
    </div>
</div>
